jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager
  

  release:
    machine: true
    steps:
      - checkout
      - run: | 
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker build -t $DOCKER_USERNAME/django.nv .
          docker push $DOCKER_USERNAME/django.nv

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1 || true
          when: always

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is a deploy step."
          when: always

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build 
      - release:
          requires:
            - build
      - integration:
          requires:
            - test
      - prod:
          type: approval
          requires:
            - integration
