jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager
   
  oast: 
    machine: true
    steps:
      - checkout
      - run: docker run -v $(pwd):/src --rm -v hysnsec/safety check -r requirements.txt --json | tee oast-results.json
      - store_artifacts:
          path: oast-results.json
          destination: safety-artifact
  

  release:
    machine: true
    steps:
      - checkout
      - run: | 
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker build -t $DOCKER_USERNAME/django.nv .
          docker push $DOCKER_USERNAME/django.nv

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: 
          command: |
            echo "This is an integration step"
            exit 1

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - when: 
          condition:
            equal: [ main, << pipeline.git.branch >> ]
      - run:
          command: |
            echo "This is a deploy step."

  artifact:
    docker:
      - image: python:3.6
    working_directory: /tmp
    steps: 
      - run:
          command: |
            echo "hello world" > hello.txt
      - store_artifacts:
          path: hello.txt

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build 
      - release:
          requires:
            - build
      - integration:
          requires:
            - test
            - release
      - prod:
          type: approval
          requires:
            - integration
      - artifact
