jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager
   
  oast_safety: 
    machine: true
    steps:
      - checkout
      
      - run: 
          command: docker run -v $(pwd):/src --rm -v hysnsec/safety check -r requirements.txt --json | tee oast-results.json
          when: on_fail
        
      - store_artifacts:
          path: oast-results.json
          destination: oast-artifact
          when: always

  oast_retire: 
    machine: true
    steps:
      - checkout
      
      - run: 
          command: docker run --rm -v $(pwd):/src -w /src hysnsec/retire --outputformat json --outputpath retirejs-results.json --severity high
          when: on_fail
        
      - store_artifacts:
          path: retire-js-results.json
          destination: oast-artifacts
          when: always

  release:
    machine: true
    steps:
      - checkout
      - run: | 
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker build -t $DOCKER_USERNAME/django.nv .
          docker push $DOCKER_USERNAME/django.nv

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: 
          command: |
            echo "This is an integration step"
            exit 1
          when: on_fail

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - when: 
          condition:
            equal: [ main, << pipeline.git.branch >> ]
      - run:
          command: |
            echo "This is a deploy step."
         

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build 
      - oast_safety:
          requires:
            - build 
      - oast_retire:
          requires:
            - build 
      - release:
          requires:
            - oast_safety
            - oast_retire
            - test
      - integration:
          requires:
            - release
      - prod:
          type: approval
          requires:
            - integration
